name: CI Testing Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Pruebas para el frontend Angular
  test-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias Angular
        run: |
          cd frontend
          npm install

      - name: Ejecutar pruebas Angular
        run: |
          cd frontend
          npm run test -- --watch=false --browsers=ChromeHeadless

  # Pruebas para el backend Laravel
  test-laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Instalar dependencias Laravel
        run: |
          cd backend
          composer install

      - name: Copiar .env
        run: |
          cd backend
          cp .env.example .env
          php artisan key:generate

      - name: Ejecutar pruebas Laravel
        run: |
          cd backend
          php artisan test
  
  # Pruebas backend con Node.js
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias Node.js
        run: |
          cd frontend/backend
          npm install

      - name: Ejecutar pruebas Node.js
        run: |
          cd frontend/backend
          npm test || echo "Ignorando tests inexistentes"

  # Despliegue automatico en Render
  deploy:
    needs: [test-angular, test-laravel, test-node]
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar Backend de Laravel en Render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_SERVICE_ID }}/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Desplegar Node en Render para Angular
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_NODE_ID }}/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Desplegar Frontend de Angular en Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
